main: me.gnat008.perworldinventory.PerWorldInventory
version: 0.0.2
name: PerWorldInventory
author: Gnat008

commands:
  pwi:
    description: Commands for PerWorldInventory
    aliases: [perworldinventory]
    
permissions:
  perworldinventory.admin:
    default: op
    children:
      perworldinventory.convert: true
      perworldinventory.reload: true
  perworldinventory.convert:
    default: false
  perworldinventory.reload:
    default: false
